# Generated by Django 3.1 on 2020-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201002_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='descripion',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
