# Generated by Django 3.1 on 2020-10-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201003_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='aa',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
