# Generated by Django 3.1 on 2020-10-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='aa',
        ),
    ]
