# Generated by Django 3.1 on 2020-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201003_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='picture',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
