# Generated by Django 3.1 on 2020-10-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user_watchlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.user'),
            preserve_default=False,
        ),
    ]
