# Generated by Django 3.1 on 2020-10-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201009_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
