# Generated by Django 3.1 on 2020-10-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201013_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to='auctions.user'),
            preserve_default=False,
        ),
    ]
