# Generated by Django 3.1 on 2020-10-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201016_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_made', to='auctions.comment'),
            preserve_default=False,
        ),
    ]
