# Generated by Django 3.1 on 2020-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auction_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='comment',
        ),
        migrations.AddField(
            model_name='auction',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_made', to='auctions.Comment'),
        ),
    ]
